#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DRY_RUN=0
SYNC_CODEX=1
SYNC_CLAUDE=1
FAILURES=0

CODEX_TARGET="${CODEX_TARGET:-$HOME/.codex/AGENTS.md}"
CLAUDE_TARGET="${CLAUDE_TARGET:-$HOME/.claude/CLAUDE.md}"
STRICT_SYNC="${STRICT_SYNC:-0}"
CLAUDE_SOURCE="${CLAUDE_SOURCE:-$REPO_ROOT/AGENTS.md}"
RUNTIME_BUNDLE="${RUNTIME_BUNDLE:-1}"

usage() {
  cat <<'EOF'
Usage: bash scripts/sync-agent-configs.sh [options]

Options:
  --dry-run                 Print actions without writing files.
  --no-codex                Skip Codex sync.
  --no-claude               Skip Claude sync.
  --codex-target <path>     Override Codex target file path.
  --claude-target <path>    Override Claude target file path.
  --claude-source <path>    Override Claude source file path.
  --no-runtime-bundle       Disable runtime bundling; copy files directly.
  -h, --help                Show this help.

Environment variables:
  CODEX_TARGET              Same as --codex-target.
  CLAUDE_TARGET             Same as --claude-target.
  CLAUDE_SOURCE             Same as --claude-source.
  RUNTIME_BUNDLE            1 to bundle AGENTS + RULES into target files (default), 0 to copy directly.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --no-codex)
      SYNC_CODEX=0
      shift
      ;;
    --no-claude)
      SYNC_CLAUDE=0
      shift
      ;;
    --codex-target)
      CODEX_TARGET="${2:-}"
      shift 2
      ;;
    --claude-target)
      CLAUDE_TARGET="${2:-}"
      shift 2
      ;;
    --claude-source)
      CLAUDE_SOURCE="${2:-}"
      shift 2
      ;;
    --no-runtime-bundle)
      RUNTIME_BUNDLE=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

build_runtime_bundle() {
  local base_src="$1"
  local out_file="$2"
  local label="$3"
  local rule_file

  if [[ ! -f "$base_src" ]]; then
    echo "[$label] base source missing: $base_src" >&2
    FAILURES=$((FAILURES + 1))
    return 0
  fi

  {
    echo "# Runtime Rules Bundle"
    echo
    echo "This file is auto-generated by scripts/sync-agent-configs.sh."
    echo "Repository root: $REPO_ROOT"
    echo
    echo "Runtime behavior:"
    echo "- Treat this file as the primary rule source."
    echo "- Use absolute paths below when loading repository files."
    echo
    echo "Absolute repository paths:"
    echo "- $REPO_ROOT/AGENTS.md"
    echo "- $REPO_ROOT/CODEX.md"
    echo "- $REPO_ROOT/CLAUDE.md"
    echo "- $REPO_ROOT/CHATGPT.md"
    echo "- $REPO_ROOT/RULES/"
    echo "- $REPO_ROOT/PROMPTS/"
    echo "- $REPO_ROOT/templates/"
    echo
    echo "---"
    echo
    echo "## Base Rules Source: $base_src"
    echo
    cat "$base_src"
    echo
    echo "---"
    echo
    echo "## Inlined RULES Files"
    for rule_file in "$REPO_ROOT"/RULES/*.md; do
      if [[ -f "$rule_file" ]]; then
        echo
        echo "### $(basename "$rule_file")"
        echo
        cat "$rule_file"
      fi
    done
  } > "$out_file"
}

copy_or_bundle() {
  local src="$1"
  local dst="$2"
  local label="$3"
  local temp_output=""

  local dst_dir
  dst_dir="$(dirname "$dst")"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run][$label] mkdir -p $dst_dir"
    if [[ "$RUNTIME_BUNDLE" == "1" ]]; then
      echo "[dry-run][$label] bundle $src + RULES/*.md -> $dst"
    else
      echo "[dry-run][$label] cp $src $dst"
    fi
    return 0
  fi

  mkdir -p "$dst_dir"

  if [[ "$RUNTIME_BUNDLE" == "1" ]]; then
    temp_output="$(mktemp)"
    if ! build_runtime_bundle "$src" "$temp_output" "$label"; then
      rm -f "$temp_output"
      FAILURES=$((FAILURES + 1))
      return 0
    fi
    if cp "$temp_output" "$dst"; then
      echo "[$label] bundled and synced: $dst"
    else
      echo "[$label] bundle sync failed: $dst" >&2
      FAILURES=$((FAILURES + 1))
    fi
    rm -f "$temp_output"
  else
    if [[ ! -f "$src" ]]; then
      echo "[$label] source file missing: $src" >&2
      FAILURES=$((FAILURES + 1))
      return 0
    fi
    if cp "$src" "$dst"; then
      echo "[$label] synced: $dst"
    else
      echo "[$label] sync failed: $dst" >&2
      FAILURES=$((FAILURES + 1))
    fi
  fi
}

if [[ "$SYNC_CODEX" -eq 1 ]]; then
  copy_or_bundle "$REPO_ROOT/AGENTS.md" "$CODEX_TARGET" "codex"
fi

if [[ "$SYNC_CLAUDE" -eq 1 ]]; then
  copy_or_bundle "$CLAUDE_SOURCE" "$CLAUDE_TARGET" "claude"
fi

echo "Sync finished."

if [[ "$FAILURES" -gt 0 ]]; then
  if [[ "$STRICT_SYNC" == "1" ]]; then
    echo "Sync completed with $FAILURES failure(s)." >&2
    exit 1
  fi
  echo "Sync completed with $FAILURES warning(s). Set STRICT_SYNC=1 to fail on warning." >&2
fi
